
FROM mcr.microsoft.com/windows/servercore/iis


EXPOSE 80


COPY ./index.html C:/inetpub/wwwroot/index.html


CMD ["powershell.exe", "Start-Service", "W3SVC", "-Verbose", "&&", "ping", "-t", "localhost"]

